project_id = "zpryngvwbybpshsfeqaz"

[functions.sheets-bridge]
verify_jwt = false

[functions.notify-service-event]
verify_jwt = false

[functions.record-attendance]
verify_jwt = false

[functions.get-service-pdf]
verify_jwt = false

[functions.format-complaint]
verify_jwt = false

[functions.get-service-payments]
verify_jwt = false

[functions.get-service-photos]
verify_jwt = false
