
CREATE TABLE public.queue_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  queue_number integer GENERATED BY DEFAULT AS IDENTITY,
  display_code text,
  status text NOT NULL DEFAULT 'waiting',
  client_name text NOT NULL,
  contact_number text,
  device_type text,
  brand text,
  model text,
  chief_complaint text,
  form_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  service_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT ON public.queue_entries TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.queue_entries_queue_number_seq TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.queue_entries TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.queue_entries_queue_number_seq TO authenticated;
GRANT ALL ON public.queue_entries TO service_role;

ALTER TABLE public.queue_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can submit a queue entry"
  ON public.queue_entries FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    status IN ('waiting') AND service_id IS NULL
  );

CREATE POLICY "Anyone can read active queue entries"
  ON public.queue_entries FOR SELECT
  TO anon, authenticated
  USING (status IN ('waiting', 'proceed'));

CREATE POLICY "Admins can read all queue entries"
  ON public.queue_entries FOR SELECT
  TO authenticated
  USING (public.is_admin_or_management(auth.uid()));

CREATE POLICY "Admins can update queue entries"
  ON public.queue_entries FOR UPDATE
  TO authenticated
  USING (public.is_admin_or_management(auth.uid()))
  WITH CHECK (public.is_admin_or_management(auth.uid()));

CREATE POLICY "Admins can delete queue entries"
  ON public.queue_entries FOR DELETE
  TO authenticated
  USING (public.is_admin_or_management(auth.uid()));

CREATE OR REPLACE FUNCTION public.queue_entries_before_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.display_code IS NULL OR NEW.display_code = '' THEN
    NEW.display_code := 'Q-' || lpad(NEW.queue_number::text, 4, '0');
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER queue_entries_before_insert_trg
BEFORE INSERT ON public.queue_entries
FOR EACH ROW EXECUTE FUNCTION public.queue_entries_before_insert();

CREATE TRIGGER queue_entries_set_updated_at
BEFORE UPDATE ON public.queue_entries
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER PUBLICATION supabase_realtime ADD TABLE public.queue_entries;
ALTER TABLE public.queue_entries REPLICA IDENTITY FULL;
